version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mariadb
    volumes:
      - ./opt:/opt
      - ./var/www:/var/www/html
      - ./var/log:/var/log

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
